redirects:
  license: ./README.md
  1-axon-framework/introduction: ./README.md
  1-axon-framework/getting-started: ./introduction/quick-start.md
  1.1-concepts/architecture-overview: ./introduction/architecture-overview/architecture-overview.md
  1.1-concepts/messaging-concepts: ./configuring-infrastructure-components/messaging-concepts/messaging-concepts.md
  1.2-domain-logic/command-model: ./implementing-domain-logic/command-handling/command-handling.md
  1.2-domain-logic/event-handling: ./implementing-domain-logic/event-handling/event-handling.md
  1.2-domain-logic/query-handling: ./implementing-domain-logic/query-handling/query-handling.md
  1.2-domain-logic/sagas: ./implementing-domain-logic/complex-business-transactions/complex-business-transactions.md
  1.2-domain-logic/deadlines: ./configuring-infrastructure-components/deadlines.md
  1.2-domain-logic/testing: ./implementing-domain-logic/command-handling/testing.md
  1.3-infrastructure-components/command-dispatching: ./configuring-infrastructure-components/command-processing/command-processing.md
  1.3-infrastructure-components/event-processing: ./configuring-infrastructure-components/event-processing/event-processing.md
  1.3-infrastructure-components/query-processing: ./configuring-infrastructure-components/query-processing.md
  1.3-infrastructure-components/repository-and-event-store:  ./configuring-infrastructure-components/event-processing/event-bus-and-event-store.md
  1.3-infrastructure-components/spring-boot-autoconfiguration: ./setting-up/spring-boot.md
  1.4-advanced-tuning/advanced-customizations: ./operations-guide/production-considerations/production-considerations.md
  1.4-advanced-tuning/performance-tuning: ./operations-guide/setting-up-axon-server/tuning.md
  1.4-advanced-tuning/metrics-and-monitoring: ./operations-guide/production-considerations/monitoring-and-metrics.md
  2-axon-server/about: ./introduction/axon-server.md
  2-axon-server/getting-started: ./setting-up/starting-the-axon-server.md
  2-axon-server/architecture: ./introduction/axon-server.md
  2.1-setup/starting-axonserver: ./operations-guide/setting-up-axon-server/launch.md
  2.1-setup/configuration: ./operations-guide/setting-up-axon-server/tuning.md
  2.1-setup/clustering: ./operations-guide/setting-up-axon-server/axon-server-clustering.md
  2.1-setup/multi-context: ./operations-guide/setting-up-axon-server/multi-context.md
  2.2-operations/backups: ./operations-guide/setting-up-axon-server/backups.md
  2.2-operations/monitoring: ./operations-guide/setting-up-axon-server/monitoring.md

